// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MPPIS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210127091136_tokens")]
    partial class tokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.RDBMS.Entities.DayPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("DayPrice");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("house_number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("street");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vilage");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lviv",
                            District = "Mostisky",
                            HouseNumber = "53",
                            Street = "Sagaydachnogo",
                            Village = "Tvirzha"
                        },
                        new
                        {
                            Id = 2,
                            City = "Lviv",
                            District = "Mostisky",
                            HouseNumber = "53",
                            Street = "Sagaydachnogo",
                            Village = "Tvirzha"
                        });
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<decimal>("CountProduction")
                        .HasColumnType("decimal")
                        .HasColumnName("count_production");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DayPriceId")
                        .HasColumnType("int")
                        .HasColumnName("day_price_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DayPriceId");

                    b.HasIndex("UserId");

                    b.ToTable("StorageData");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.RouteDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("route");

                    b.HasKey("Id");

                    b.ToTable("RouteDay");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.TokenRefresh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TokenRefresh");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("lastname");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("middlename");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordhash");

                    b.Property<DateTime>("RegisteredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("registered_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@gmail.com",
                            FirstName = "Tester",
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            LastName = "Testerovich",
                            LocationId = 1,
                            MiddleName = "Test",
                            PasswordHash = "AQAAAAEAACcQAAAAEFw+rTIwRCL5oz56L3HkEDdQbKiuyNDd7TJ7uZriAqfezgzMBWC8vWcC5G+tjwHTWg==",
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            LastName = "Adminovich",
                            LocationId = 2,
                            MiddleName = "Adminovski",
                            PasswordHash = "AQAAAAEAACcQAAAAEHVvDS3fEyq1+u+m7+aXCO7NV4gKVfYvCUZq37okoSgKS9WZvojQD2VQY6bg+4tMDQ==",
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Product", b =>
                {
                    b.HasOne("Domain.RDBMS.Entities.DayPrice", "DayPrice")
                        .WithMany("StorageData")
                        .HasForeignKey("DayPriceId")
                        .IsRequired();

                    b.HasOne("Domain.RDBMS.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("DayPrice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.TokenRefresh", b =>
                {
                    b.HasOne("Domain.RDBMS.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.User", b =>
                {
                    b.HasOne("Domain.RDBMS.Entities.Location", "Location")
                        .WithOne("User")
                        .HasForeignKey("Domain.RDBMS.Entities.User", "LocationId")
                        .IsRequired();

                    b.HasOne("Domain.RDBMS.Entities.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.DayPrice", b =>
                {
                    b.Navigation("StorageData");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Location", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RDBMS.Entities.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
